spring.application.name=bella-pizza-rest

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=das_bella_pizza;encrypt=false
spring.datasource.username=sa
spring.datasource.password=DB_Password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

# Servidor
server.port=8082

# Logging
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
